version: '3'
services:
  db:
    restart: always
    image: postgres:latest
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "54322:5432"
    environment:
      - POSTGRES_USER:'docker_user'
      - POSTGRES_PASSWORD:'docker'
      - POSTGRES_DB:'docker'

  books-service:
    restart: always
    build: .
    ports:
      - "8000:8000"
    links:
      - db
